export const landingCopy = {
  en: {
    title: 'Subscription Manager — A little more clarity.',
    description:
      'Keep subscriptions, recurring costs and renewal dates in one calm place. Start free, without connecting your bank.',
    skip: 'Skip to content',
    features: 'Features',
    pricing: 'Pricing',
    guides: 'Guides',
    open: 'Open app',
    eyebrow: 'LESS ADMIN. MORE PEACE OF MIND.',
    headline: 'All your subscriptions.',
    accent: 'A little more clarity.',
    intro:
      'The little things add up. Keep track of what you pay, see what’s coming, and make room for what matters.',
    start: 'Start tracking for free',
    explore: 'Take a closer look',
    reassurance: 'No bank connection. No credit card. Just a clearer picture.',
    preview: 'A glimpse of your everyday',
    example: 'Interactive preview · sample data',
    overview: 'Your overview',
    monthly: 'Monthly',
    yearly: 'Yearly',
    period: 'View spending by period',
    monthTotal: 'Estimated monthly spend',
    yearTotal: 'Estimated yearly spend',
    active: '4 active subscriptions',
    next: 'COMING UP NEXT',
    tomorrow: 'Tomorrow',
    inFive: 'In 5 days',
    renewal: 'Spotify renews',
    perMonth: '/ month',
    perYear: '/ year',
    subscriptions: 'Your subscriptions',
    all: 'All subscriptions',
    categories: ['Entertainment', 'Music', 'Cloud storage', 'Productivity'],
    renews: 'Renews',
    dates: ['Oct 21', 'Oct 8', 'Oct 12', 'Oct 24'],
    previewNote: 'Your subscriptions, finally in one place.',
    previewAside: 'A small habit. A clearer month.',
    benefits: [
      'Unlimited subscriptions',
      'Multiple currencies',
      'Your data, exportable',
    ],
    featureLabel: '01 / A LITTLE LESS TO REMEMBER',
    featureTitle: 'Keep the good subscriptions.',
    featureAccent: 'Lose the mental tabs.',
    featureIntro:
      'From your first cup of coffee to your last streaming service. A home for the costs that keep coming back.',
    reminderTitle: 'Before it renews. Not after.',
    reminderBody:
      'Get renewal and free-trial reminders through Bark. Give yourself time to decide what stays.',
    reminderApp: 'RENEWAL REMINDER',
    reminderTime: 'Just now',
    reminderExample: 'Your Spotify subscription renews tomorrow.',
    reminderDetail: '$10.99 · Monthly',
    captureTitle: 'Less typing. More done.',
    captureBody:
      'Drop in a screenshot or describe a subscription. AI prepares a draft, and you give it the final word.',
    capturePrompt: '“Netflix, $15.49 a month, renews October 21.”',
    captureDraft: 'Ready for your review',
    captureField: 'Monthly · Entertainment',
    smallFeatures: [
      [
        'One view. Every currency.',
        'Bring different currencies into one overview with exchange-rate conversion.',
      ],
      [
        'Pick up where you left off.',
        'Sign in to sync your subscriptions across your devices.',
      ],
      [
        'Always yours to take.',
        'Import and export your data as JSON. Keep a copy whenever you like.',
      ],
    ],
    toolsLabel: 'FITS INTO YOUR EVERYDAY',
    toolsTitle: 'Your tools.\nOn the same page.',
    toolsBody:
      'Connect your agent with API and MCP access. Look up subscriptions, review spending, and keep things up to date from the tools you already use.',
    toolsLink: 'Explore the integrations',
    toolsNote: 'API & MCP access included in both plans',
    priceLabel: '02 / ONE LESS SUBSCRIPTION',
    priceTitle: 'A subscription manager.',
    priceAccent: 'Without another subscription.',
    priceIntro:
      'Start with everything you need. Pay once if you’d like a little more.',
    free: 'Free',
    freeSubtitle: 'A good place to get organized.',
    forever: 'USD · no monthly fee',
    freeItems: [
      'Unlimited subscriptions & categories',
      'Cloud sync & Bark renewal reminders',
      'Multi-currency overview & JSON export',
      '10 AI captures per month · API & MCP',
    ],
    premium: 'A little extra clarity.',
    once: 'USD · one-time payment',
    premiumItems: [
      'Everything in Free',
      '300 AI captures every month',
      'Advanced spending reports',
      'Downloadable PDF reports',
    ],
    priceLink: 'Explore lifetime Premium',
    priceNote:
      'Lifetime access for the life of the service. AI quotas renew monthly.',
    faqLabel: 'THE SMALL PRINT, IN PLAIN WORDS',
    faqTitle: 'Good questions.',
    faqs: [
      [
        'Do I need an account to get started?',
        'No. Start tracking in your browser without signing up. Create an account when you want cloud sync and account features such as AI capture and API access.',
      ],
      [
        'Does it connect to my bank?',
        'No. You add the subscriptions you want to track, manually or with AI-assisted entry. Spending totals are estimates based on your records, not verified bank transactions.',
      ],
      [
        'How do renewal reminders work?',
        'Connect Bark in notification settings and choose when you want to be reminded. Cloud reminders require an account and a configured Bark endpoint.',
      ],
      [
        'Can I take my data with me?',
        'Yes. JSON import and export are included in Free. Export before switching browsers or domains to move records that are only stored locally.',
      ],
    ],
    closing: 'Less to keep in your head.',
    closingAccent: 'More room for everything else.',
    closingNote: 'Start with one subscription. The rest will feel easier.',
    footer: 'A little tool for a little more peace of mind.',
    source: 'Source code',
    madeBy: 'Made by Jerry Lu',
  },
  'zh-CN': {
    title: 'Subscription Manager — 每一笔订阅，心中有数。',
    description:
      '把订阅、持续开销和续费日期放在一处。免费开始，无需关联银行账户，让每一笔订阅都心中有数。',
    skip: '跳转到正文',
    features: '功能',
    pricing: '价格',
    guides: '使用指南',
    open: '进入应用',
    eyebrow: '少一点惦记，多一点从容',
    headline: '每一笔订阅，',
    accent: '都心中有数。',
    intro:
      '那些不知不觉累积的小开销，值得被好好看见。记录你在付什么，知道何时续费，把空间留给真正在意的事。',
    start: '免费开始整理',
    explore: '往下看看',
    reassurance: '无需关联银行，无需信用卡。从第一笔订阅开始。',
    preview: '你的日常，可以这样清楚',
    example: '交互预览 · 示例数据',
    overview: '开销概览',
    monthly: '每月',
    yearly: '每年',
    period: '切换开销统计周期',
    monthTotal: '预计每月支出',
    yearTotal: '预计每年支出',
    active: '4 个进行中的订阅',
    next: '下一笔续费',
    tomorrow: '明天',
    inFive: '5 天后',
    renewal: 'Spotify 即将续费',
    perMonth: '/ 月',
    perYear: '/ 年',
    subscriptions: '我的订阅',
    all: '全部订阅',
    categories: ['影音娱乐', '音乐', '云存储', '效率工具'],
    renews: '下次续费',
    dates: ['10 月 21 日', '10 月 8 日', '10 月 12 日', '10 月 24 日'],
    previewNote: '零散的订阅，终于有了一处归属。',
    previewAside: '一个小习惯，一个更清楚的月份。',
    benefits: ['不限订阅数量', '多币种统一查看', '数据随时导出'],
    featureLabel: '01 / 少一件需要惦记的事',
    featureTitle: '留下喜欢的订阅，',
    featureAccent: '放下琐碎的惦记。',
    featureIntro:
      '从每天用的效率工具，到周末看的流媒体。让每一笔持续发生的开销，都有迹可循。',
    reminderTitle: '在续费前想起，而不是扣款后。',
    reminderBody:
      '通过 Bark 接收续费与免费试用到期提醒。留一点时间，决定什么值得继续。',
    reminderApp: '续费提醒',
    reminderTime: '刚刚',
    reminderExample: '你的 Spotify 订阅将于明天续费。',
    reminderDetail: '$10.99 · 按月付费',
    captureTitle: '少填几个格子，多省一点时间。',
    captureBody: '贴一张截图，或说一句话。AI 整理成订阅草稿，最后由你确认。',
    capturePrompt: '“Netflix 每月 15.49 美元，10 月 21 日续费。”',
    captureDraft: '已整理，等你确认',
    captureField: '每月 · 影音娱乐',
    smallFeatures: [
      [
        '不同币种，同一份清楚。',
        '按汇率换算，把不同币种的订阅汇总到一个开销视图。',
      ],
      ['换个设备，接着整理。', '登录账户，让订阅在你的不同设备之间保持同步。'],
      [
        '你的数据，随时带走。',
        '支持 JSON 导入与导出，想留一份备份时，随时都可以。',
      ],
    ],
    toolsLabel: '融入你已有的习惯',
    toolsTitle: '和你习惯的工具，\n一起工作。',
    toolsBody:
      '通过 API 和 MCP 连接你的 Agent。在熟悉的工具里查询订阅、了解开销，也能让它帮忙更新记录。',
    toolsLink: '了解如何连接',
    toolsNote: 'Free 与 Premium 均包含 API 和 MCP 权限',
    priceLabel: '02 / 不再多订一个',
    priceTitle: '管理你的订阅，',
    priceAccent: '不成为另一笔月费。',
    priceIntro: '从完整的基础功能开始。想再轻松一点，只需付费一次。',
    free: '免费版',
    freeSubtitle: '从容整理，从这里开始。',
    forever: '美元 · 没有每月账单',
    freeItems: [
      '不限订阅与分类数量',
      '云同步与 Bark 续费提醒',
      '多币种概览与 JSON 导出',
      '每月 10 次 AI 录入 · API 与 MCP',
    ],
    premium: '多一点便利，多一份清楚。',
    once: '美元 · 一次付费',
    premiumItems: [
      '包含免费版全部功能',
      '每月 300 次 AI 录入',
      '进阶开销分析报告',
      '完整报告下载为 PDF',
    ],
    priceLink: '了解终身 Premium',
    priceNote: '在本服务持续运营期间享有终身权益，AI 额度按月更新。',
    faqLabel: '把你关心的事，说明白',
    faqTitle: '你可能还想知道。',
    faqs: [
      [
        '一定要注册才能使用吗？',
        '不用。你可以直接在浏览器里开始记录。需要云同步，以及 AI 录入、API 等账户功能时，再创建账户即可。',
      ],
      [
        '需要关联我的银行账户吗？',
        '不需要。你可以手动添加订阅，也可以让 AI 辅助录入。页面中的开销是根据你记录的订阅估算的，不代表银行实际扣款。',
      ],
      [
        '续费提醒是怎么发送的？',
        '在通知设置中连接 Bark，并选择提醒时间。云端提醒需要登录账户，并配置有效的 Bark 推送地址。',
      ],
      [
        '以后还能把数据带走吗？',
        '当然。免费版就支持 JSON 导入与导出。更换浏览器或域名前，记得先导出仅保存在本地的记录，再到新环境导入。',
      ],
    ],
    closing: '少一点放在心上的琐事，',
    closingAccent: '多一点留给生活的空间。',
    closingNote: '从第一笔订阅开始，让接下来的每个月都更清楚。',
    footer: '一个小工具，让生活少一点惦记。',
    source: '开源代码',
    madeBy: '由 Jerry Lu 制作',
  },
};
