export const landingCopy = {
  en: {
    title: 'SteadyRenew — Track subscriptions and renewal dates',
    description: 'Track subscription costs, check renewal dates, and get reminders before you pay. Free to use, with no bank connection required.',
    skip: 'Skip to content',
    features: 'Features', pricing: 'Pricing', guides: 'Blog', docs: 'Docs', open: 'Open app',
    eyebrow: 'SUBSCRIPTION TRACKER',
    headline: 'What are you paying for?',
    accent: 'When does it renew?',
    intro: 'Keep your subscriptions in one list. See your monthly total and get a reminder before the next renewal.',
    start: 'Start for free', explore: 'See the app', reassurance: 'No account needed to start.',
    example: 'App screenshot · sample data',
    previewAlt: 'SteadyRenew dashboard with a monthly spending total, currency and category filters, subscription cards with renewal dates, and an add subscription button.',
    previewZoom: 'Open the full-size app screenshot',
    benefits: ['Unlimited subscriptions', 'Multiple currencies', 'JSON import and export'],
    featureLabel: 'FEATURES', featureTitle: 'Record the cost.', featureAccent: 'Remember the renewal.',
    featureIntro: 'Add subscriptions manually, or use a screenshot to fill in the details.',
    reminderTitle: 'Get a reminder before renewal',
    reminderBody: 'Connect Bark and choose how far in advance to be notified. Reminders also cover free trials, so you have time to cancel before the first charge.',
    captureTitle: 'Add a subscription from a screenshot',
    captureBody: 'Upload a screenshot or type a description. AI extracts the details into a draft for you to check before saving.',
    smallFeatures: [
      ['Compare costs across currencies', 'Choose a display currency to convert and total your subscriptions.'],
      ['Sync across devices', 'Sign in to keep your subscription records available on your other devices.'],
      ['Import and export your records', 'Download a JSON backup, or import your records from another browser.'],
    ],
    toolsLabel: 'INTEGRATIONS', toolsTitle: 'Manage subscriptions\nfrom your AI tools',
    toolsBody: 'Connect Claude, ChatGPT, or Gemini to SteadyRenew through MCP. Ask about upcoming renewals, check spending, or update a subscription. You can also use the API with your own tools.',
    toolsLink: 'Connection instructions', toolsNote: 'API and MCP access are included in Free.',
    toolsDiagram: 'SteadyRenew connects through MCP to Claude, ChatGPT, and Gemini.',
    priceLabel: 'PRICING', priceTitle: 'A subscription manager.', priceAccent: 'Without another subscription.',
    priceIntro: 'The core features are free. Premium adds more AI captures and spending reports for a one-time payment.',
    free: 'Free', freeSubtitle: 'For tracking your subscriptions.', forever: 'USD · free',
    freeItems: ['Unlimited subscriptions & categories', 'Cloud sync & Bark renewal reminders', 'Multi-currency overview & JSON export', '10 AI captures per month · API & MCP'],
    premium: 'More AI captures and detailed reports.', once: 'USD · one-time payment',
    premiumItems: ['Everything in Free', '300 AI captures every month', 'Advanced spending reports', 'Downloadable PDF reports'],
    priceLink: 'View Premium', priceNote: 'Lifetime access lasts for the life of the service. AI quotas reset monthly.',
    faqLabel: 'FAQ', faqTitle: 'Common questions',
    faqs: [
      ['Do I need an account?', 'No. You can start recording subscriptions in your browser. Sign in when you need cloud sync, AI capture, or API access.'],
      ['Does it connect to my bank?', 'No. You add subscriptions manually or with AI-assisted entry. Spending totals are estimates based on those records, not bank transactions.'],
      ['How do reminders work?', 'Sign in and connect Bark in notification settings, then choose when to be reminded. Cloud reminders need a valid Bark push address.'],
      ['Can I move my data?', 'Yes. Free includes JSON import and export. Before changing browsers or domains, export any records stored only on that device.'],
    ],
    closing: 'Start with the subscriptions', closingAccent: 'you’re already paying for.',
    closingNote: 'Open the app and add your first one.',
    footer: 'Track costs and renewal dates.', source: 'GitHub', madeBy: 'Made by Jerry Lu',
  },
  'zh-CN': {
    title: 'SteadyRenew — 记录订阅开销和续费日期',
    description: '集中记录订阅，查看每月开销，在续费前收到提醒。免费使用，无需关联银行账户。',
    skip: '跳转到正文', features: '功能', pricing: '价格', guides: '博客', docs: '文档', open: '进入应用',
    eyebrow: '订阅管理', headline: '每月花了多少，', accent: '下次什么时候续费。',
    intro: '把视频会员、软件、云存储记在一起，看看每月一共花了多少。快续费时，提前收到提醒。',
    start: '免费开始使用', explore: '看看实际界面', reassurance: '不用注册就能开始。',
    example: '实际应用截图 · 示例数据',
    previewAlt: 'SteadyRenew 实际管理界面：每月总支出、币种和分类筛选、带有续费日期的订阅卡片，以及添加订阅入口。',
    previewZoom: '打开完整尺寸的应用截图',
    benefits: ['不限订阅数量', '支持多币种', 'JSON 导入与导出'],
    featureLabel: '功能', featureTitle: '记下每笔开销，', featureAccent: '到期前提醒你。',
    featureIntro: '可以自己填，也可以用截图录入。保存前都能检查和修改。',
    reminderTitle: '续费前，收到提醒',
    reminderBody: '连接 Bark，设置提前几天提醒。免费试用也能设到期提醒，想取消的话，来得及在扣款前处理。',
    captureTitle: '截张图，少填几个字段',
    captureBody: '上传截图，或者用一句话描述订阅。AI 提取名称、金额和周期，生成草稿，检查后再保存。',
    smallFeatures: [
      ['不同币种，汇总查看', '选一个常用币种，按汇率换算，查看订阅的总开销。'],
      ['换个设备也能看', '登录账户后，订阅记录会在不同设备间同步。'],
      ['备份和迁移', '导出 JSON 留一份备份，换浏览器时也可以直接导入。'],
    ],
    toolsLabel: '连接工具', toolsTitle: '在常用的 AI 工具里\n也能管理订阅',
    toolsBody: '通过 MCP 连接 Claude、ChatGPT 或 Gemini，查询快到期的订阅、统计开销，或修改记录。也可以用 API 连接你自己的工具。',
    toolsLink: '了解如何连接', toolsNote: '免费版就能使用 API 和 MCP。',
    toolsDiagram: 'SteadyRenew 通过 MCP 连接 Claude、ChatGPT 和 Gemini。',
    priceLabel: '价格', priceTitle: '管理你的订阅，', priceAccent: '不成为另一笔月费。',
    priceIntro: '日常记录免费使用。需要更多 AI 录入次数和开销报告，可以一次付费升级。',
    free: '免费版', freeSubtitle: '记录订阅需要的功能，都在这里。', forever: '美元 · 免费使用',
    freeItems: ['不限订阅与分类数量', '云同步与 Bark 续费提醒', '多币种概览与 JSON 导出', '每月 10 次 AI 录入 · API 与 MCP'],
    premium: '更多 AI 录入次数，以及详细的开销报告。', once: '美元 · 一次付费',
    premiumItems: ['包含免费版全部功能', '每月 300 次 AI 录入', '进阶开销分析报告', '完整报告下载为 PDF'],
    priceLink: '查看 Premium', priceNote: '在本服务持续运营期间享有终身权益，AI 额度按月更新。',
    faqLabel: '常见问题', faqTitle: '使用前你可能想问',
    faqs: [
      ['一定要注册吗？', '不用。你可以直接在浏览器里记录订阅。需要云同步、AI 录入或 API 时，再登录账户。'],
      ['需要关联银行账户吗？', '不需要。订阅由你手动添加，或用 AI 辅助录入。页面上的开销根据记录估算，不是银行实际扣款。'],
      ['提醒怎么发给我？', '登录后，在通知设置里连接 Bark，填入有效的推送地址，并选择提前多久提醒。'],
      ['换浏览器，数据怎么办？', '免费版支持 JSON 导入与导出。更换浏览器或域名前，先导出仅保存在本地的记录，再到新环境导入。'],
    ],
    closing: '从你正在付费的', closingAccent: '第一笔订阅开始。', closingNote: '打开应用，填上名称、金额和续费日期。',
    footer: '记录订阅开销和续费日期。', source: 'GitHub', madeBy: '由 Jerry Lu 制作',
  },
};
