export const pricingCopy = {
 en: {
  back: 'Back to your subscriptions', label: 'A LITTLE LESS TO KEEP TRACK OF',
  title: 'Manage subscriptions.', accent: 'Skip one more.',
  intro: 'Your subscription manager shouldn’t be another subscription. Keep the essentials free. Make room for a little more, once.',
  free: 'Free, and useful.', freeNote: 'Unlimited subscriptions. Cloud sync. Renewal and trial reminders. Your data is always yours to export.',
  compare: 'Compare the details', pass: 'THE LIFETIME PASS', once: 'USD · paid once',
  premiumIntro: 'Less busywork. A clearer picture.', included: 'Everything in Free, plus',
  ai: '300 AI captures every month', aiNote: 'Text or screenshots → drafts you review.',
  reports: 'A deeper look at your spending', reportsNote: 'Cost breakdowns, renewal patterns and insights.',
  pdf: 'Reports worth keeping', pdfNote: 'Download your full report as a PDF.',
  buy: 'Get lifetime Premium', login: 'Sign in to get Premium', active: 'Your lifetime pass is active',
  processing: 'Opening secure checkout…', secure: 'Secure checkout by Stripe', noRenew: 'No renewals. No recurring fees.',
  unavailable: 'Checkout is not available yet', error: 'We couldn’t open checkout. Please try again.',
  retry: 'Try again', pending: 'Confirming your payment…',
  waiting: 'Your upgrade is still being confirmed. Please refresh your account in a moment; don’t pay again.',
  cancelled: 'Checkout was cancelled. You can continue with Free or try again.',
  test: 'Test checkout · no real charge', stamp: 'ONE PAYMENT\nMORE CLARITY',
  detailLabel: 'THE SAME GOOD FOUNDATION', detailTitle: 'More helpful. Not more restrictive.',
  detailIntro: 'Pay for the extras, not for access to your own data.', capability: 'What you get',
  rows: ['Subscriptions & categories', 'Cloud sync & multiple devices', 'Renewal & free-trial reminders', 'Multi-currency & basic statistics', 'JSON import & export', 'Core API & MCP access', 'AI captures / calendar month', 'Advanced reports & PDF'],
  unlimited: 'Unlimited', yes: 'Included', api: 'Same access', no: '—',
  limits: 'API & MCP: the same 60 requests per minute and 5 active keys per account on both plans. No monthly request allowance; advanced analytics follow the report entitlement. Limits help contain abuse, including leaked keys.',
  quota: 'AI quotas reset on the first of each month (UTC). Failed parses are returned to your quota. Temporary provider outages or service-wide safety limits can pause AI; manual entry stays available.',
  faqLabel: 'BEFORE YOU MAKE IT OFFICIAL', faqTitle: 'A few fair questions.',
  faqs: [
   ['Does lifetime really mean one payment?', 'Yes. $9 USD is a one-time purchase, not a recurring subscription. Premium stays attached to your account for the lifetime of this service. Monthly AI limits still apply.'],
   ['Do I have to upgrade to use the app?', 'No. Tracking, sync, reminders, basic statistics and raw data export remain free. Premium adds more AI captures and advanced reports.'],
   ['Will you connect to my bank?', 'No bank connection is needed. Reports estimate costs from the subscriptions you record; they are not verified bank transactions.'],
   ['Can I use it on another device?', 'Yes. Sign in with the same account to use your Premium access. You don’t need to purchase it again.'],
  ], footer: 'Built for the things you subscribe to. Not to become one of them.',
 },
 zh: {
  back: '返回我的订阅', label: '少一件需要惦记的事',
  title: '管理你的订阅，', accent: '不再多订一个。',
  intro: '订阅管理工具，不该成为另一笔月费。基础功能始终免费；只需付费一次，让整理更轻松一点。',
  free: '免费，也足够好用。', freeNote: '不限订阅数量，支持云同步、续费和试用到期提醒。数据属于你，随时可以导出。',
  compare: '看看具体差别', pass: '一张终身通行证', once: '美元 · 一次付费',
  premiumIntro: '少些手动整理，多些心中有数。', included: '包含 Free 全部功能，以及',
  ai: '每月 300 次 AI 录入', aiNote: '文字或截图，变成由你确认的订阅草稿。',
  reports: '更清楚地了解持续开销', reportsNote: '费用拆解、续费分布与进阶分析。',
  pdf: '一份可以留存的报告', pdfNote: '将完整分析下载为 PDF。',
  buy: '获取终身 Premium', login: '登录并获取 Premium', active: '你的终身 Premium 已生效',
  processing: '正在打开安全付款页面…', secure: '由 Stripe 安全处理付款', noRenew: '不自动续费，没有每月账单。',
  unavailable: '付款暂未开放', error: '暂时无法打开付款页面，请重试。', retry: '重试',
  pending: '正在确认付款结果…', waiting: '权益仍在确认中，请稍后刷新账户，不要重复付款。',
  cancelled: '已退出付款，你可以继续免费使用，或重新尝试。',
  test: '测试付款 · 不会实际扣款', stamp: '只付一次\n心中有数',
  detailLabel: '一样完整的基础体验', detailTitle: '多一点帮助，少一点限制。',
  detailIntro: '为额外的便利付费，而不是为取回自己的数据。', capability: '你能使用的能力',
  rows: ['订阅与分类数量', '云同步与多设备', '续费与试用到期提醒', '多币种与基础统计', 'JSON 导入与导出', '基础 API 与 MCP', 'AI 录入／自然月', '进阶报告与 PDF'],
  unlimited: '不限', yes: '包含', api: '相同权限', no: '—',
  limits: 'API／MCP 两档均为每账户每分钟 60 次请求、5 个有效密钥，不设月度调用额度；进阶分析接口与报告权益一致。限流用于防刷，也帮助限制密钥泄露后的滥用。',
  quota: 'AI 额度于每月 1 日（UTC）重置，解析失败会返还额度。服务商故障或全站安全限额可能暂时影响 AI；手动录入始终可用。',
  faqLabel: '付款之前，说明白一点', faqTitle: '你可能还想知道。',
  faqs: [
   ['终身版真的只付一次吗？', '是的，9 美元一次买断，不是自动续费订阅。在本服务持续运营期间，Premium 权益一直绑定你的账户。AI 仍按月提供额度。'],
   ['不升级，还能正常使用吗？', '当然。记录订阅、同步、提醒、基础统计与原始数据导出均免费。Premium 增加 AI 额度和进阶报告。'],
   ['需要连接银行账户吗？', '不需要。报告根据你录入的订阅估算费用，不代表银行已核实的实际扣款。'],
   ['换设备需要重新买吗？', '不需要。使用同一个账户登录，即可使用已有的 Premium 权益。'],
  ], footer: '帮你管理订阅，而不成为你的又一项订阅。',
 },
};
